### ISSUE TITLE
[Question] PostgresError: password authentication failed for user "freshyfresh"

### ISSUE THREAD

**Issue by lydonchandra** [CodingGarden/fresh-spots#67]
Using docker db setup, I keep getting password authentication failure when doing

`deno task migrate:up`

while i can connect directly using psql ok
`psql "postgres://freshyfresh:freshyfreshsecret@localhost:5432/fresh-spots"`

what am i missing ?

```
PostgresError: password authentication failed for user "freshyfresh"
    at Connection.#authenticateWithSasl (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:654:15)
    at async Connection.#authenticate (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:547:33)
    at async Connection.#startup (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:412:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:491:11)
    at async Connection.query (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:943:7)
    at async Client.#executeQuery (https://deno.land/x/postgres@v0.16.1/client.ts:245:12)
    at async Client.queryObject (https://deno.land/x/postgres@v0.16.1/client.ts:433:12)
    at async PgConnection.executeQuery (file:///home/don/d/fresh-spots/app/db/PostgresDriver.ts:78:22)
    at async PgConnection.connection.executeQuery (https://cdn.jsdelivr.net/npm/kysely@0.21.4/dist/esm/driver/runtime-driver.js:74:24)
    at async https://cdn.jsdelivr.net/npm/kysely@0.21.4/dist/esm/query-executor/query-executor-base.js:34:28
```

**Comment by lydonchandra** [comment]
Fixed by updating postgres to 0.17.0, 
the latest postgres `v15`  uses `password_encryption = 'scram-sha-256'` by default, which is only supported in v0.17.0

https://deno.land/x/postgres@v0.17.0/mod.ts

https://github.com/denodrivers/postgres/commit/3f41b49b09462a6b44c5bb5e31eada5663362729
